# This file configures the Dart analyzer for static code analysis.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - .idea/**
    - .vscode/**
    - linux/**                 # Exclude native Linux files if not relevant to Dart analysis
    - *.g.dart                 # Exclude generated files
    - **/*.freezed.dart        # Exclude Freezed-generated files

  language:
    strict-inference: true      # Requires explicit type annotations for improved type safety
    strict-casts: true          # Disallow implicit type casting
    strict-raw-types: true      # Prevent using raw types for generics

linter:
  rules:
    # Recommended lint rules for Flutter development
    prefer_const_constructors: true       # Enforce the use of `const` constructors when possible
    prefer_const_literals_to_create_immutables: true # Use immutable literals with `const`
    use_key_in_widget_constructors: true  # Enforce constructors with `Key`
    prefer_final_fields: true             # Encourage using `final` for non-reassigned fields
    avoid_unnecessary_containers: true    # Prevent wrapping widgets in unnecessary containers
    always_use_package_imports: true      # Enforce importing from `package` for clarity

    # Additional rules for better practices
    avoid_print: true                     # Discourage using `print`; use proper logging instead
    annotate_overrides: true              # Ensure overridden methods are annotated with `@override`
    avoid_empty_else: true                # Avoid empty `else` blocks
    sort_child_properties_last: true      # Sort widget child properties last for readability

    # Uncomment as needed for stricter rules:
    # prefer_single_quotes: true           # Enforce single quotes for strings
    # avoid_classes_with_only_static_members: true # Discourage static-only classes
    # unnecessary_null_checks: true       # Prevent redundant null checks in non-nullable code

# Additional resources:
# Lint rules: https://dart.dev/lints
# Analysis options: https://dart.dev/guides/language/analysis-options


