# Configures the Dart analyzer for static code analysis in Flutter.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - .idea/**
    - .vscode/**
    - linux/**
    - macos/**
    - web/**
    - windows/**
    - test/**.mocks.dart
    - *.g.dart
    - **/*.freezed.dart

  language:
    strict-inference: true
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    always_use_package_imports: true
    avoid_print: true
    annotate_overrides: true
    avoid_empty_else: true
    sort_child_properties_last: true
    avoid_redundant_argument_values: true
    unnecessary_null_checks: true
    prefer_typing_uninitialized_variables: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_dynamic_calls: true
    prefer_asserts_with_message: true
    prefer_is_not_empty: true
